### PR TITLE
capitalize tooltip

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
Some more feedback from Rasmus

image

### CODE REVIEW

**Review by madsnedergaard — APPROVED** [review]
LGTM

**Comment by VIKTORVAV99** [comment]
How does this affect non-Germanic languages?

**Comment by madsnedergaard** [comment]
> How does this affect non-Germanic languages?

Uf, good thought - didn't think of that :D 

But looking at the languages we have it should be fine:
- it works for Greek `cap('πυρηνική') --> 'Πυρηνική'`
- it works for Russian `cap('биотопливо') --> 'Биотопливо'`
- arabic has no capital letters
- Chinese has no capital letters
- Japanese has no capital letters

**Comment by VIKTORVAV99** [comment]
> > How does this affect non-Germanic languages?
> 
> Uf, good thought - didn't think of that :D
> 
> But looking at the languages we have it should be fine:
> 
> * it works for Greek `cap('πυρηνική') --> 'Πυρηνική'`
> * it works for Russian `cap('биотопливо') --> 'Биотопливо'`
> * arabic has no capital letters
> * Chinese has no capital letters
> * Japanese has no capital letters

Nice and I assume they don't generate a bunch of errors 😅

**Pull request merged**
