### PR TITLE
Mobile modals part IV: FAQ

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Issue

https://linear.app/electricitymaps/issue/ELE-1340/[ui]-mobile-modals

## Description

Adds the FAQ Modal.

### Preview

Screenshot 2022-12-28 at 23 35 41

### CODE REVIEW

**Comment by tonypls** [comment]
I'm not sure how to access this in mobile

**Comment by tonypls** [comment]
Ah it needs the previous PR, can't really test them in isolation though

**Comment by madsnedergaard** [comment]
> Ah it needs the previous PR, can't really test them in isolation though
Oh yeah, didn't think of that! Will merge the rest today :)

**Comment by tonypls** [comment]
FAQ's all look great, just the consistency of the text color of these buttons that could be improved:
image

**Comment by tonypls** [comment]
Oh and the tooltips for consumption / production and zone / country are waiting for a hover, we might want to do a mobile friendly interaction too

**Comment by madsnedergaard** [comment]
> Oh and the tooltips for consumption / production and zone / country are waiting for a hover, we might want to do a mobile friendly interaction too

I have created a Linear issue for this: https://linear.app/electricitymaps/issue/ELE-1546/ensure-tooltips-can-be-opened-on-mobile

**Comment by madsnedergaard** [comment]
I have added the green background to clearly indicate that something is "activated", which was hard to determine before IMO. 

Group 1

Just for fun, I also tried turning them into Switches instead, as that makes it more clear that it is something you can toggle on/off. I think that works pretty well, but didn't want to spend time on actually designing and implementing it right now, so still using the above solution :)

Screenshot 2023-01-05 at 12 30 00

**Comment by tonypls** [comment]
Beautiful!

**Review by tonypls — APPROVED** [review]

**Pull request merged**
