### PR TITLE
disclaimer

### PR DESCRIPTION
**Pull request by tonypls**
## Issue
https://linear.app/electricitymaps/issue/ELE-1522/get-disclaimer-flag-working-again

## Description

Re implement displaying disclaimers, not sure what it used to look like but it's currently only visible on two zones so I put it at the bottom.

### Preview

image

### CODE REVIEW

**Comment by madsnedergaard** [comment]
Oh, sorry that I forgot to share more context! Here's the old one, implemented as a tooltip - but if it's too much work, we can also roll with this version for now :) 
https://github.com/electricitymaps/electricitymaps-contrib/pull/3091

**Comment by tonypls** [comment]
Ahh cool so it was the feature that aligned with Mathilde's suggestion, should be easy enough to use our tooltip component :D

**Comment by madsnedergaard** [comment]
> Ahh cool so it was the feature that aligned with Mathilde's suggestion, should be easy enough to use our tooltip component :D

Yup, I also replied that on the Slack thread, but guess it drowned in the messages somewhere 😄 

Screenshot 2023-01-03 at 22 15 39

**Comment by tonypls** [comment]
> > Ahh cool so it was the feature that aligned with Mathilde's suggestion, should be easy enough to use our tooltip component :D
> 
> Yup, I also replied that on the Slack thread, but guess it drowned in the messages somewhere 😄
> 
> Screenshot 2023-01-03 at 22 15 39

Yes I remember the thread, I just hadn't connected the dots that this was the same feature!

**Review by madsnedergaard — APPROVED** [review]
LGTM! It would be nice if clicking on the trigger on mobile opened the tooltip (both here and in toggles), but it's not supported in Radix and requires some work, so I have a created https://linear.app/electricitymaps/issue/ELE-1546/ensure-tooltips-can-be-opened-on-mobile for it :)

**Pull request merged**
