### PR TITLE
Cleans up ESLint rules

### PR DESCRIPTION
**Pull request by madsnedergaard**
## Description

Changes from "all" to "recommended" for all plugins.
Adjusts some rules.
Also added the `.vscode` folder that was gitignored and a symlink so you can open both `web` and `/` in VSCode and still get the same settings.

### TBD

There's some rules here about larger patterns we should discuss!

1. **Filenames** Keep
`PascalCase` for components, `camelCase` for everything else?
(The is default in the starter, but we can do whatever)

2. **Declaring components** Discuss
It can be done in a bunch of different ways in JS. Should we enforce strictness around this?
Starter uses `react/function-component-definition: [“error”, {“namedComponents”: “function-declaration”}]`which means this:

```js
// incorrect (arrow function)
const CoolComponent = ({name}) => <div>{name}</div>

// correct
function CoolComponent({ name }) {
  return <div>{name}</div>;
}
```
3. **explicit-function-return-type** Remove
```
// incorrect because it doesn't have a :boolean return type explicit
function isBoolean(value) {
  return true;
}
```

4. type alias Discuss

5. **Absolute imports** Prefix with ~
To prefix imports or not?
E.g. `import X from @components/whatever` vs `import X from components/whatever`
If yes, use `@` or `~`?

### CODE REVIEW

**Comment by tonypls** [comment]
These might be nice while we build:
```
   "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-empty-function": "off",
    ```

**Comment by tonypls** [comment]
Do you think it would be nice to document a style guide of sorts of these rules in the readme or similar?

**Comment by madsnedergaard** [comment]
> Do you think it would be nice to document a style guide of sorts of these rules in the readme or similar?

Hmm, I imagined that the rules would actually be the guide - as there's only one way to do things, and ESLint will tell you if you're doing it any other way 😉 
With that said, https://linear.app/electricitymaps/issue/ELE-1361/[documentation]-code-standards should probably cover parts of this :)

**Comment by tonypls** [comment]
I'm okay with old function definitions for components if we all want 👍

**Review by tonypls — APPROVED** [review]

**Comment by madsnedergaard** [comment]
> I'm okay with old function definitions for components if we all want 👍

Let's try it and be ready to change if we don't like it - should be very easy to refactor as ESLint can autofix it :)

**Pull request merged**
