### PR TITLE
🎁 Improve tooltip interactivity on mobile

### PR DESCRIPTION
**Pull request by Kongkille**
## Description

Had a lot of issues navigating with the tooltips on mobile, specifically closing and opening tooltips was annoying. I figured it might be good to have a dismiss button alongside the tooltips so users can close it.

In terms of code, in this implementation the button doesn't actually do anything, but magically closes the tooltip because the event is considered a onLeave. That might not work as flawlessly on capacitor?

- Adds some CSS styling to make interactions more intuitive on mobile
- Adds an X button which can be used to close down the tooltip on mobile

### Preview

image

### CODE REVIEW

**Review by tonypls — COMMENTED** [review]
Could we capitalise Wind, Gas etc. in the tooltip? It's different from the axis label but I think it makes sense as they're functioning as a title for the tooltips and will be more consistent with the tooltips below.

**Comment by Kongkille** [comment]
> Could we capitalise Wind, Gas etc. in the tooltip? It's different from the axis label but I think it makes sense as they're functioning as a title for the tooltips and will be more consistent with the tooltips below.

Sure, for most languages that is probably fine

**Comment by tonypls** [comment]
> > Could we capitalise Wind, Gas etc. in the tooltip? It's different from the axis label but I think it makes sense as they're functioning as a title for the tooltips and will be more consistent with the tooltips below.
> 
> Sure, for most languages that is probably fine

Ah yeah languages are tricky!

**Comment by tonypls** [comment]
It was probably web mobile view specific but there were cases when the zone tooltip remained open after the left panel covered the screen.  My feedback around capitalisation is covered in #108

**Review by tonypls — APPROVED** [review]
LGTM

**Pull request merged**
