### PR TITLE
add all the flags

### PR DESCRIPTION
**Pull request by Kongkille**
Adds all the flags

### CODE REVIEW

**Comment by Kongkille** [comment]
Merging as I don't think this requires a review.

One note for ourselves is to be sure we use all the flag sizes. I don't think we are using 128??

**Comment by madsnedergaard** [comment]
Makes sense. Also, food for thought: could we use the flag emojis for this instead? 🤔

**Comment by Kongkille** [comment]
> Makes sense. Also, food for thought: could we use the flag emojis for this instead? 🤔

That is actually a really good point. Do you see any reason why not?

**Comment by madsnedergaard** [comment]
I have no idea how to do it in a smart way though, but let's look into it at some point! :)

**Pull request merged**
